name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9, 3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: 'pyproject.toml'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        package_json_file: js/package.json

    - name: Install dependencies
      run: make develop

    - name: Build
      run: make build

    - name: Lint
      run: make lint

    - name: Test
      run: make tests
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload test results (Python)
      uses: actions/upload-artifact@v4
      with:
        name: py-test-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: junit.xml
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload test results (JS)
      uses: actions/upload-artifact@v4
      with:
        name: js-test-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: js/junit.xml
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
            **/junit.xml
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Twine check
      run: make dist

