name: Publish Wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
  workflow_dispatch:

concurrency:
  group: docs
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: cp README.md docs/wiki/Home.md
      - uses: Andrew-Chen-Wang/github-wiki-action@64efa0a9436db17670a2259e0ac249d6f08bb352 # v5
        with:
          path: docs/wiki
